name: "Download Release and Upload"

on: workflow_dispatch

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    # Retrieve ipa file from GitHub artifacts
    - name: Download release asset
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: tags/v1.0.6
        file: app-x86_64-debug.apk
        target: app-x86_64-debug.apk
        token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

    - name: list downloaded release
      run: ls -ltrh
    
    # Upload ipa file to Fiebase
    - name: Upload APK artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_IOS_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: "app-arm64-v8a-debug.apk"