name: "Build & Release Android iOS Flutter App"

on: workflow_dispatch

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        # with:
        #   flutter-version: '2.2.0'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: collect ipa artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa-apk
          # Path to the release files
          path: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  release:
    name: Release ipa to Firebase
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    
    # Retrieve ipa file from GitHub artifacts
    - uses: actions/checkout@v2
    - name: Get release-ipa-apk from artifacts
      uses: actions/download-artifact@v2
      with:
        name: release-ipa-apk

    # Upload ipa file to Fiebase
    - name: Upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_IOS_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: ios-developers
        file: "app.ipa,app-arm64-v8a-debug.apk"